namespace GitHubIntegration
{
    using System;
    using System.Threading.Tasks;

    class Program
    {
        static void Main(string[] args)
        {
            string githubToken = args[0];
            MainAsync(githubToken).Wait();
            Console.WriteLine("Completed");
            Console.ReadKey();
        }

        private static async Task MainAsync(string githubToken)
        {
            var repository = new GitHubRepositoryClient(githubToken, "iarovyi", "Playground");
            var branch = "master";
            string filePath = "hello/foo.txt";

            await repository.CreateFile(filePath, "new file", "autogenerated creation commit", branch);
            await repository.UpdateFile(filePath, "updated file", "autogenerated update commit", branch);
            await repository.UpsertFile(filePath, "updated again file", "autogenerated upsert commit", branch);
            await repository.DeleteFile(filePath, "autogenerated deletion commit", branch);
        }
    }
}
